on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Step 3: Cache Node.js dependencies
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 5: Build the application
    - name: Build Application
      run: npm run build

    # Step 6: Deploy to VPS
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USER }}
      run: |
        # Start ssh-agent and add the private key
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$SSH_PRIVATE_KEY")

        # Deploy the build to the VPS
        rsync -avz --delete --partial --compress dist/ $USERNAME@$HOST:/var/www/syncronlabs.com
